spring.application.name=xslt-transformer

# ActiveMQ
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/xslt_audit

# Queue Names
app.queue.input=Amq-json-Q1
app.queue.dlq=Amq-DLQ
app.queue.intermediate.prefix=Amq-json-in-
app.queue.output.prefix=Amq-xml-out-

# External XSLT folder path
app.xslt.external-path=/Users/saivardhanreddynarra/Desktop/ApacheCamel_EIP/XSLT_transformation/XSLT_Files/

# Camel
camel.springboot.main-run-controller=true

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true